package de.hsa.games.fatsquirrel.core.entity;

public enum EntityType {
    BADBEAST, GOODBEAST, BADPLANT, GOODPLANT, WALL, MASTERSQUIRREL, MINISQUIRREL, HANDOPERATEDMASTERSQUIRREL, PACSQUIRREL ,EMPTY
}
